# Generated by Django 4.2.2 on 2023-07-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'In progress')], default=1),
        ),
    ]
