# Generated by Django 4.2.2 on 2023-07-07 02:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completer',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('deleted user'), related_name='completer', to=settings.AUTH_USER_MODEL, verbose_name='Completer'),
        ),
        migrations.AddField(
            model_name='task',
            name='completion_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=models.SET('deleted user'), related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
