# Generated by Django 4.2.2 on 2023-07-11 01:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_task_completer_task_completion_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 2}, null=True, on_delete=models.SET('deleted user'), related_name='completer', to=settings.AUTH_USER_MODEL, verbose_name='Completer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'In progress'), (3, 'Completed')], default=1),
        ),
    ]
